name: E2E Fixture

on:
  workflow_dispatch:

jobs:
  upterm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start upterm session
        uses: ./
        with:
          wait-timeout-minutes: 5
